### ISSUE TITLE
startRequestId used in csend should be optional

### ISSUE THREAD

**Issue by gadicc** [kiri-art/docker-diffusers-api#7]
As reported in https://discord.com/channels/771185033779609630/775513653461516299/1037716160168329287

```
 Exception occurred while handling uri: 'http://0.0.0.0:8000/' Traceback (most recent call last):
 File "handle_request", line 81, in handle_request FutureStatic,
 File "server.py", line 36, in inference output = user_src.inference(model_inputs)
 File "/api/app.py", line 140, in inference startRequestId = call_inputs.get("startRequestId", None) AttributeError: 'NoneType' object has no attribute 'get'
 [2022-11-03 13:11:11 +0000] - (sanic.access)[INFO][127.0.0.1:55872]: POST http://0.0.0.0:8000/ 500 139
```

Will fix this!  In the meantime:

```js
{
  // CallInputs section (MODEL_ID, etc)
  startRequestId: "ANYTHING"
}
```

It used to be (optional) but due to a different feature that obviously broke this.

**Comment by gadicc** [comment]
Oh actually, this wasn't broken, the particular user above was calling with the wrong inputs (no `callInputs` key).
