### ISSUE TITLE
Clearer error when container's data isn't in `{ modelInputs, callInputs }` format.

### ISSUE THREAD

**Issue by gadicc** [kiri-art/docker-diffusers-api#9]
Not at all obvious from [this discord message](https://discord.com/channels/771185033779609630/1034722380825776138/1038093469069099028):

```
Starting worker [6] { "prompt": "a sunset" } [2022-11-04 14:02:16 +0000] [6] [ERROR] Exception occurred while handling uri: 'http://0.0.0.0:8000/' Traceback (most recent call last): File "handle_request", line 81, in handle_request FutureStatic, File "server.py", line 36, in inference output = user_src.inference(model_inputs) File "/api/app.py", line 144, in inference startRequestId = call_inputs.get("startRequestId", None) AttributeError: 'NoneType' object has no attribute 'get' [2022-11-04 14:02:16 +0000] - (sanic.access)[INFO][127.0.0.1:53964]: POST http://0.0.0.0:8000/ 500 139
```

**Comment by gadicc** [comment]
Included in https://github.com/kiri-art/docker-diffusers-api/commit/8eca8fedd95a325ebc9c3298a072dc0849ee4347#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959R170.
